### ISSUE TITLE
Execution environment needs to be more clearly defined

### ISSUE THREAD

**Issue by heuermh** [Steven-N-Hart/VariantDB_Challenge#2]
From the Rules page:

> This is important because all challenges will be replicated on an identical piece of hardware to they can be systematically compared.

Scalable systems for variant analysis, especially those well suited to query over the whole 1000 Genomes dataset, may need more flexibility in execution environment than a single piece of hardware.

For example, while [ADAM](https://github.com/bigdatagenomics/adam) runs fine on a single large machine, we would prefer to run over an Apache Spark cluster backed by a distributed file system such as [Apache Hadoop](https://wiki.apache.org/hadoop/HDFS) or [Tachyon/Alluxio](http://www.alluxio.org).

**Comment by Steven-N-Hart** [comment]
You're absolutely right.  I'll need to add more details about how to best address this.  I know we will need to use a spark-type approach and a distributed file system. (I'm working on my own MongoDB/Hadoop/Spark implementation as we speak.) The real trick, and the true value, is how to design and build the system appropriately.  

I was able to get the The [instance](https://github.com/Steven-N-Hart/VariantDB_Challenge/wiki/Frequently-Asked-Questions#2-what-size-box-will-you-be-doing-testing-on) without really trying too hard.  But if your group intends to add to the challenge, we will get the desired configuration.  If we can have a soup to nuts documentation of how to set everything up from scratch and get the challenge results it shouldn't be too big of a deal.  The purpose is really to leverage the skill sets of different groups that know their systems the best, without having one person/group learn 20 different languages - of which they will only have a superficial understanding.  I don't want reasonable hardware limitations to become an impetus for joining the challenge, so I am removing that statement from the Rules page.
